# Pipeline Evaluation — chequeo manual post-clasificación

Objetivo: en 5 minutos verificar que las 3 tablas canónicas tienen sentido.  
Corre cada sección de arriba a abajo. Si algo se ve raro, es el lugar para anotarlo.

In [1]:
import sys
sys.path.insert(0, '../src')

import pandas as pd

pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_rows', 60)

classified = pd.read_csv('../data/processed/reviews_classified.csv')
agg        = pd.read_csv('../data/processed/aggregated.csv')
ins        = pd.read_csv('../data/processed/insights.csv')

has_text   = classified[classified['has_text'] == True].copy()
cl         = classified[classified['sentiment'].notna()].copy()

print(f"reviews_classified : {len(classified):>4} rows  |  classified: {len(cl)}  |  rating-only: {classified['sentiment'].isna().sum()}")
print(f"aggregated         : {len(agg):>4} rows")
print(f"insights           : {len(ins):>4} rows")

reviews_classified :  250 rows  |  classified: 155  |  rating-only: 95
aggregated         :    4 rows
insights           :   27 rows

---
## 1 · Sanidad de datos — conteos y nulos

In [2]:
# Rows per business
classified.groupby('business_name').agg(
    total=('review_id','count'),
    with_text=('has_text','sum'),
    classified=('sentiment', lambda s: s.notna().sum()),
    rating_only=('sentiment', lambda s: s.isna().sum()),
    errors=('sentiment', lambda s: (s == 'error').sum()),
).assign(pct_classified=lambda d: (d['classified'] / d['with_text'] * 100).round(1))

,total,with_text,classified,rating_only,errors,pct_classified
business_name,,,,,,
El Mesón de Gauss,50,30,29,21,0,96.7
IDA Restaurant Bar,100,53,53,47,0,100.0
Mitica,50,40,40,10,0,100.0
Vittorio Ristorante,50,33,33,17,0,100.0

In [3]:
# Duplicate review_ids?
dupes = classified['review_id'].duplicated().sum()
print(f"Duplicate review_ids: {dupes}")

# Nulls in classification fields (should only be on rating-only rows)
cl_fields = ['sentiment','main_topic','subtopic','urgency','is_actionable','classification_confidence']
print("\nNulls per field (classified rows only):")
print(cl[cl_fields].isna().sum())

Duplicate review_ids: 0

Nulls per field (classified rows only):
sentiment                     0
main_topic                    0
subtopic                     21
urgency                       0
is_actionable                 0
classification_confidence     0
dtype: int64

---
## 2 · Distribuciones — sentiment / topic / urgency / confianza

In [4]:
# Sentiment breakdown per business
(
    cl.groupby(['business_name','sentiment'])
    .size()
    .unstack(fill_value=0)
    .assign(total=lambda d: d.sum(axis=1))
    .assign(
        pct_pos=lambda d: (d['positive']/d['total']*100).round(1),
        pct_neg=lambda d: (d['negative']/d['total']*100).round(1),
    )
)

sentiment            negative  neutral  positive  total  pct_pos  pct_neg
business_name
El Mesón de Gauss          18        1        10     29     34.5     62.1
IDA Restaurant Bar         13        0        40     53     75.5     24.5
Mitica                      6        0        34     40     85.0     15.0
Vittorio Ristorante         5        0        28     33     84.8     15.2

In [5]:
# Topic distribution — global
cl['main_topic'].value_counts()

main_topic
Food Quality              46
Overall Experience        39
Staff Attitude            38
Menu & Options            10
Service Speed              9
Ambiance                   6
Price / Value              4
Hygiene & Cleanliness      2
Booking & Reservations     1
Name: count, dtype: int64

In [6]:
# Urgency distribution
cl['urgency'].value_counts()

urgency
low       110
medium     37
high        8
Name: count, dtype: int64

In [7]:
# Confidence distribution
print(cl['classification_confidence'].describe().round(3))
print(f"\nLow confidence (<0.70): {(cl['classification_confidence'] < 0.70).sum()} reviews")

count    155.000
mean       0.952
std        0.050
min        0.800
25%        0.900
50%        0.950
75%        1.000
max        1.000
Name: classification_confidence, dtype: float64

Low confidence (<0.70): 0 reviews

---
## 3 · Spot-check — muestras aleatorias para revisión manual

Leé cada texto y verificá que el label tenga sentido. Si algo está mal anotalo más abajo.

In [8]:
SAMPLE_N = 20  # cambiá este número si querés ver más
RANDOM_SEED = 42

sample = cl.sample(SAMPLE_N, random_state=RANDOM_SEED)[
    ['business_name','clean_text','sentiment','main_topic','subtopic','urgency','is_actionable','classification_confidence']
].reset_index(drop=True)

sample

,business_name,clean_text,sentiment,main_topic,subtopic,urgency,is_actionable,classification_confidence
0,El Mesón de Gauss,"Mala atención, la comida no nos gustó tampoco, los wraps secos el gohan que no es gohan l ensalada César desabrida",negative,Food Quality,multiple food quality issues,medium,True,0.90
1,Vittorio Ristorante,"excelente atención, exquisitos los tagliatelle con mariscos! el crepe de dulce de leche y el tiramisú muy buenos!! l...",positive,Food Quality,Specific dishes,low,False,0.90
2,IDA Restaurant Bar,"Primera visita y muy grata! La comida riquísima, hay una entrada súper rica. Hasta el pan es casero. La atención un ...",positive,Overall Experience,lighting improvement suggestion,low,True,0.90
3,IDA Restaurant Bar,Excelente. Muy muy recomendable. Una experiencia muy agradable y una comida exquisita.,positive,Overall Experience,pleasant experience and exquisite food,low,False,1.00
4,Mitica,": ""Quiero compartir mi experiencia en Mítica. Hicimos una reserva para 8 personas para el menú ejecutivo el día ante...",positive,Booking & Reservations,Executive menu availability,medium,True,0.90
5,El Mesón de Gauss,"Vinimos con unos amigos, y NO HAY PIZZAS! lo peor es que no te advierte cuando te indican que abras la carta. Y tamp...",negative,Menu & Options,unavailable items and lack of notification,medium,True,0.90
6,Mitica,"Hermoso lugar, primera vez que voy y quedé encantada. La atención de los chicos muy buena y Milagros, la recepcionis...",positive,Staff Attitude,friendly and attentive staff,low,False,0.90
7,Vittorio Ristorante,Fui desde el primer día....y lo sigo eligiendo,positive,Overall Experience,NaN,low,False,1.00
8,Vittorio Ristorante,"Excelente todo !!! Muy rica la comida. Andrés, uno de los mozos, un crack muy amable y gentil. Los felicito.",positive,Staff Attitude,specific staff member praise,low,False,0.85
9,El Mesón de Gauss,"Solo café , pésimo,quemado ,lástima porque trabajan Ardu que es un café excelente",negative,Food Quality,burnt coffee,medium,True,0.95
10,IDA Restaurant Bar,"Excelente ambiente, musica, todo en gral.",positive,Ambiance,music and atmosphere,low,False,1.00
11,Vittorio Ristorante,Siempre lo pasamos bien. Precios accesibles. Carta q tiene de todo,positive,Overall Experience,consistently good experience,low,False,0.90
12,El Mesón de Gauss,Excelente servicio,positive,Staff Attitude,quality of service,low,False,1.00
13,El Mesón de Gauss,Fuimos hoy porque buscábamos donde desayunar y que tuviesen juegos para niños . encontramos comentarios de que acá t...,negative,Food Quality,thick bread and warm juice,medium,True,0.85
14,IDA Restaurant Bar,Excelente Atención y ambiente. La comida riquísima. Y el mozo Elvio súper atento!!! Súper recomendable.,positive,Overall Experience,"Excellent service, food, and ambiance",low,False,1.00
15,IDA Restaurant Bar,Bruno y Elvio nos atendieron muy bien es un gusto venir,positive,Staff Attitude,attentive staff,low,True,1.00
16,IDA Restaurant Bar,10/10 ❤️,positive,Overall Experience,NaN,low,False,1.00
17,Mitica,Un lugar diferente! Ya desde el ingreso uno se siente bien atendido en un ambiente muy agradable. La atención de Pau...,positive,Overall Experience,Excellent dining experience,low,False,1.00
18,Mitica,Fui a almorzar algo liviano para poder seguir. Siempre voy y como unas tostadas excelentes con palta y huevo. No me ...,negative,Menu & Options,item availability by time,medium,True,0.95
19,Vittorio Ristorante,Excelente,positive,Overall Experience,NaN,low,False,1.00

In [9]:
# LOW CONFIDENCE — revisar estos primero (más propensos a error)
cl[cl['classification_confidence'] < 0.75][
    ['business_name','clean_text','sentiment','main_topic','urgency','classification_confidence']
].sort_values('classification_confidence').head(15)

Empty DataFrame
Columns: [business_name, clean_text, sentiment, main_topic, urgency, classification_confidence]
Index: []

In [10]:
# HIGH URGENCY — verificar que realmente sean urgentes
cl[cl['urgency'] == 'high'][
    ['business_name','clean_text','sentiment','main_topic','subtopic','urgency','is_actionable']
]

,business_name,clean_text,sentiment,main_topic,subtopic,urgency,is_actionable
38,IDA Restaurant Bar,"Fuimos anoche y realmente muy decepcionado Desde la mesa, a la moza con la mini copa de bienvenida era tan Poco que ...",negative,Food Quality,"Inedible steak, slow replacement",high,True
51,IDA Restaurant Bar,La comida más o menos y lo peor el servicio dejó muchísimo que desear. Tuvieron un accidente con un plato de bondiol...,negative,Staff Attitude,Lack of apology after incident,high,True
55,IDA Restaurant Bar,"Fuimos un viernes por la noche con mi mamá, planeando una linda ""salida de chicas"", pero lamentablemente terminamos ...",negative,Hygiene & Cleanliness,rotten food causing illness and unsafe practices,high,True
95,IDA Restaurant Bar,"Acotaron mucho la carta, y encima lo que pedíamos no tenían. Mucha demora en traernos las cosas. Casi nada de varied...",negative,Menu & Options,limited selection and unavailability of items,high,True
107,El Mesón de Gauss,"Un horror,fui con mi hija y mi nieta a merendar,dos cafe con leche,tostado tostadas fit,y criollitos,en la mitad de ...",negative,Hygiene & Cleanliness,dead fly in drink / unclean cups,high,True
124,El Mesón de Gauss,Estacionamiento poco cómodo. Buen servicio de las mozas. Muy buenos los sandwichs. Fría la cerveza. Las papas snacks...,negative,Food Quality,rancid snacks,high,True
163,Mitica,Se desentienden del Wp y las redes. Tenés que ir en persona para enterarte . Tienen el menú ejecutivo en una histori...,negative,Service Speed,2-hour wait for lunch,high,True
214,Vittorio Ristorante,"Melhorem o atendimento, fomos atendidos por um rapaz de óculos que sou super grosseiro e impaciente…",negative,Staff Attitude,rude and impatient staff,high,True

In [11]:
# NEGATIVE + ACTIONABLE — los más importantes para el reporte
cl[(cl['sentiment'] == 'negative') & (cl['is_actionable'] == True)][
    ['business_name','clean_text','main_topic','subtopic','urgency','classification_confidence']
].sort_values('urgency', ascending=False)

,business_name,clean_text,main_topic,subtopic,urgency,classification_confidence
29,IDA Restaurant Bar,"No fuimos bien atendidos, nos tomaron la mitad del pedido, al no haber opciones de platos principales vegetarianos, ...",Menu & Options,lack of vegetarian/vegan main courses and reduced menu,medium,0.90
149,El Mesón de Gauss,"Mala atención, la comida no nos gustó tampoco, los wraps secos el gohan que no es gohan l ensalada César desabrida",Food Quality,multiple food quality issues,medium,0.90
129,El Mesón de Gauss,"Anoche después de ir al teatro fuimos a comer al Mesón, pedimos lomito se demoraron una hora en traerlo, no nos ofre...",Service Speed,long wait time,medium,1.00
134,El Mesón de Gauss,No me gustó nada la comida. El lugar es lindo.,Food Quality,taste of food,medium,1.00
135,El Mesón de Gauss,"40 minutos esperando atención, el lugar no estaba lleno, estuvimos afuera una desilusión... Mala atención",Service Speed,Slow service / Waiting time,medium,1.00
136,El Mesón de Gauss,Fuimos hoy porque buscábamos donde desayunar y que tuviesen juegos para niños . encontramos comentarios de que acá t...,Food Quality,thick bread and warm juice,medium,0.85
138,El Mesón de Gauss,Me sirvieron una tabla mesón y vino: -Fria el 90% de los ingredientes salvo las rabas. -Precisamente las rabas eran ...,Food Quality,Food temperature and texture,medium,1.00
147,El Mesón de Gauss,"El lugar muy lindo, la comida buena, la atención hace que no tengas ganas de volver....",Staff Attitude,unwelcoming service,medium,0.90
148,El Mesón de Gauss,Desayune muy bien. El servicio de mozas muy flojo,Staff Attitude,waitress performance,medium,0.90
156,Mitica,Si bien el ambiente es muy lindo la taza del desayuno es muy chica y las medialunas también. No conduce la calidad d...,Food Quality,portion size,medium,0.95
125,El Mesón de Gauss,Mala relación calidad precio… 11 anillos minúsculos de rabas $28000 el 27/02/26. Valores relativos totalmente distor...,Price / Value,overpriced small portion of calamari,medium,1.00
162,Mitica,"Fuimos 2 personas comimos el menú que parecía estar bien,pero la entrada ,un tenedor sobraba La carne de cerdo sin g...",Food Quality,inedible sauce and tasteless meat,medium,0.95
175,Mitica,El cafe con leche para desayunar poco menos te lo sirven en un dedal....taza grande maestro....cobramela pero dame u...,Food Quality,portion size,medium,0.95
193,Mitica,Fui a almorzar algo liviano para poder seguir. Siempre voy y como unas tostadas excelentes con palta y huevo. No me ...,Menu & Options,item availability by time,medium,0.95
196,Mitica,"Fuimos para el 14 de febrero, el sushi nada de otro mundo. Atención muy mala, mozos desbordados con muy poco persona...",Service Speed,understaffed and overwhelmed waiters,medium,0.90
210,Vittorio Ristorante,"Muyyyy lerdos. Se demoraron 50 min para un antipasto. Resto , muy bien.",Service Speed,long wait for starter,medium,0.95
212,Vittorio Ristorante,Yo ya habia ido esta vez la tabla de mariscos que pedimos ni 5 puntos le doy No se que paso,Food Quality,seafood platter quality,medium,1.00
236,Vittorio Ristorante,Llegamos en tiempo a nuestra reserva. Pedimos entrada y platos principales. Luego de una hora 45 no habia llegado la...,Service Speed,Long wait for food,medium,1.00
127,El Mesón de Gauss,"Solo café , pésimo,quemado ,lástima porque trabajan Ardu que es un café excelente",Food Quality,burnt coffee,medium,0.95
126,El Mesón de Gauss,Medialunas y criollos de mala calidad. Café de mala calidad. Asientos y mesas desniveladas. No te pueden ofrecer un ...,Price / Value,poor value for breakfast quality and seating,medium,0.90
94,IDA Restaurant Bar,Hermoso lugar. Muy rica la comida. Poco variedad de menu,Menu & Options,lack of variety,medium,0.85
99,IDA Restaurant Bar,"Creo que fui un mal día porque me habían hecho buenos comentarios. Estuvo todo bastante lerdo, una burrata congelada...",Food Quality,"frozen food, small portions",medium,0.90
56,IDA Restaurant Bar,"Muy mala experiencia, gastarse 100.000 en una salida para no ser bien atendido es un desprecio a tu plata",Staff Attitude,poor service quality,medium,0.90
73,IDA Restaurant Bar,"La verdad es que vivo fuera del país, y cada año que vengo, me encanta volver a los lugares donde he tendido muy lin...",Staff Attitude,unwillingness to serve,medium,1.00
77,IDA Restaurant Bar,"El lugar es hermoso, la comida muy buena, pero el servicio deja mucho que desear la atención. Pongo puntaje bajo en ...",Price / Value,poor service,medium,0.90
85,IDA Restaurant Bar,Mala atención,Staff Attitude,poor attention,medium,1.00
87,IDA Restaurant Bar,Los platos de entrada superan claramente a los principales. (Aún no he probado el pulpo),Food Quality,Main course quality,medium,0.95
97,IDA Restaurant Bar,"El concepto del hotel y restaurante es muy bonito un hotel bastante cómodo y hermoso, el restaurante si debería tene...",Menu & Options,breakfast international options,medium,0.95
245,Vittorio Ristorante,Comida excelente. Un solo mozo para toda una galeria. Hace perder la experiencia. Nos fuimos sin postre porque no no...,Service Speed,lack of attention / understaffing,medium,0.95
102,El Mesón de Gauss,"Ofrecieron la carta Y no tienen nada, un desastre!",Menu & Options,Items unavailable from menu,medium,0.95
106,El Mesón de Gauss,"Una pena que un lugar tan lindo, tenga mala atención. La moza muy amable pero se olvidaron de comandar el pedido, po...",Service Speed,forgotten order and long wait,medium,1.00
117,El Mesón de Gauss,"Vinimos con unos amigos, y NO HAY PIZZAS! lo peor es que no te advierte cuando te indican que abras la carta. Y tamp...",Menu & Options,unavailable items and lack of notification,medium,0.90
118,El Mesón de Gauss,Me pedí el campero que entre otras cosas viene con jugo de naranja y dulce de leche. Me lo trajeron con agua y una m...,Food Quality,Incorrect order / Mismatched description,medium,0.95
121,El Mesón de Gauss,"La verdad totalmente decepcionado, porque fuimos recomendados porque supuestamente se come muy bien. Mucha demora en...",Service Speed,delay in food arrival,medium,0.95
95,IDA Restaurant Bar,"Acotaron mucho la carta, y encima lo que pedíamos no tenían. Mucha demora en traernos las cosas. Casi nada de varied...",Menu & Options,limited selection and unavailability of items,high,0.90
38,IDA Restaurant Bar,"Fuimos anoche y realmente muy decepcionado Desde la mesa, a la moza con la mini copa de bienvenida era tan Poco que ...",Food Quality,"Inedible steak, slow replacement",high,0.95
163,Mitica,Se desentienden del Wp y las redes. Tenés que ir en persona para enterarte . Tienen el menú ejecutivo en una histori...,Service Speed,2-hour wait for lunch,high,0.90
107,El Mesón de Gauss,"Un horror,fui con mi hija y mi nieta a merendar,dos cafe con leche,tostado tostadas fit,y criollitos,en la mitad de ...",Hygiene & Cleanliness,dead fly in drink / unclean cups,high,1.00
55,IDA Restaurant Bar,"Fuimos un viernes por la noche con mi mamá, planeando una linda ""salida de chicas"", pero lamentablemente terminamos ...",Hygiene & Cleanliness,rotten food causing illness and unsafe practices,high,1.00
214,Vittorio Ristorante,"Melhorem o atendimento, fomos atendidos por um rapaz de óculos que sou super grosseiro e impaciente…",Staff Attitude,rude and impatient staff,high,1.00
51,IDA Restaurant Bar,La comida más o menos y lo peor el servicio dejó muchísimo que desear. Tuvieron un accidente con un plato de bondiol...,Staff Attitude,Lack of apology after incident,high,0.95
124,El Mesón de Gauss,Estacionamiento poco cómodo. Buen servicio de las mozas. Muy buenos los sandwichs. Fría la cerveza. Las papas snacks...,Food Quality,rancid snacks,high,0.90

---
## 4 · Aggregated — chequeo de métricas de negocio

In [12]:
agg

,business_name,total_reviews,reviews_with_text,avg_rating,pct_positive,pct_neutral,pct_negative,top_topic_1,top_topic_2,top_topic_3,high_urgency_count,actionable_count
0,El Mesón de Gauss,50,30,3.6,34.5,3.4,62.1,Food Quality,Service Speed,Staff Attitude,2,19
1,IDA Restaurant Bar,100,53,4.4,75.5,0.0,24.5,Overall Experience,Staff Attitude,Food Quality,4,18
2,Mitica,50,40,4.6,85.0,0.0,15.0,Food Quality,Staff Attitude,Overall Experience,1,11
3,Vittorio Ristorante,50,33,4.6,84.8,0.0,15.2,Overall Experience,Food Quality,Staff Attitude,1,8

In [13]:
# Verificar que pct_positive + pct_neutral + pct_negative ≈ 100 en cada fila
agg['pct_check'] = agg['pct_positive'] + agg['pct_neutral'] + agg['pct_negative']
print("pct sum per business (expected ~100):")
print(agg[['business_name','pct_check']])

pct sum per business (expected ~100):
         business_name  pct_check
0    El Mesón de Gauss      100.0
1   IDA Restaurant Bar      100.0
2               Mitica      100.0
3  Vittorio Ristorante      100.0

---
## 5 · Insights — ranking de problemas

In [14]:
# Top issues por negocio — estas son las recomendaciones del reporte
ins.sort_values('priority_score', ascending=False)

,business_name,main_topic,mention_count,pct_negative,avg_urgency_score,actionable_count,priority_score
0,El Mesón de Gauss,Food Quality,11,63.6,1.73,7,12.10
1,El Mesón de Gauss,Service Speed,4,100.0,2.00,4,8.00
2,IDA Restaurant Bar,Menu & Options,5,80.0,2.00,4,8.00
3,Vittorio Ristorante,Service Speed,3,100.0,2.00,3,6.00
4,IDA Restaurant Bar,Staff Attitude,15,26.7,1.40,8,5.61
5,Mitica,Service Speed,2,100.0,2.50,2,5.00
6,El Mesón de Gauss,Menu & Options,2,100.0,2.00,2,4.00
7,El Mesón de Gauss,Price / Value,3,66.7,2.00,3,4.00
8,IDA Restaurant Bar,Food Quality,12,25.0,1.33,3,3.99
9,Mitica,Food Quality,13,23.1,1.23,4,3.69
10,IDA Restaurant Bar,Hygiene & Cleanliness,1,100.0,3.00,True,3.00
11,El Mesón de Gauss,Hygiene & Cleanliness,1,100.0,3.00,True,3.00
12,El Mesón de Gauss,Staff Attitude,4,50.0,1.50,2,3.00
13,IDA Restaurant Bar,Price / Value,1,100.0,2.00,True,2.00
14,Mitica,Menu & Options,2,50.0,1.50,1,1.50
15,Vittorio Ristorante,Staff Attitude,6,16.7,1.33,3,1.33
16,Vittorio Ristorante,Food Quality,10,10.0,1.10,2,1.10
17,El Mesón de Gauss,Ambiance,1,0.0,1.00,False,0.00
18,El Mesón de Gauss,Overall Experience,3,0.0,1.00,0,0.00
19,IDA Restaurant Bar,Ambiance,3,0.0,1.00,0,0.00
20,Mitica,Ambiance,2,0.0,1.00,0,0.00
21,IDA Restaurant Bar,Overall Experience,16,0.0,1.00,1,0.00
22,Mitica,Booking & Reservations,1,0.0,2.00,True,0.00
23,Mitica,Staff Attitude,13,0.0,1.00,3,0.00
24,Mitica,Overall Experience,7,0.0,1.00,0,0.00
25,Vittorio Ristorante,Overall Experience,13,0.0,1.00,0,0.00
26,Vittorio Ristorante,Menu & Options,1,0.0,1.00,False,0.00

In [15]:
# Por business — qué problema lidera en cada uno
ins.groupby('business_name').first()[['main_topic','priority_score','pct_negative','avg_urgency_score']]

,main_topic,priority_score,pct_negative,avg_urgency_score
business_name,,,,
El Mesón de Gauss,Food Quality,12.1,63.6,1.73
IDA Restaurant Bar,Menu & Options,8.0,80.0,2.00
Mitica,Service Speed,5.0,100.0,2.50
Vittorio Ristorante,Service Speed,6.0,100.0,2.00

---
## 6 · Hallazgos manuales

Usá esta celda para anotar lo que encontraste en el spot-check:

**Clasificaciones correctas:** 

**Clasificaciones dudosas o incorrectas:** 

**Patrones que el modelo no captó bien:** 

**Acciones a tomar (prompt, taxonomía, etc.):**